/* LSPedia WEB editable — datos administrados desde Publicador. */
(function(){
'use strict';
let CFG=null;
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const tx=v=>String(v==null?'':v).replace(/[\u0000-\u001F\u007F]/g,' ').trim();
const ml=v=>String(v==null?'':v).replace(/\r\n?/g,'\n').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').trim();
const at=(o,p)=>p.reduce((a,k)=>a&&typeof a==='object'?a[k]:undefined,o);
function recurso(v){v=tx(v);return v&&!/^(?:javascript|vbscript|data)\s*:/i.test(v)?v:'';}
function enlace(v){v=tx(v);return v&&/^(?:https?:\/\/|mailto:|tel:|\/|#)/i.test(v)&&!/^(?:javascript|vbscript|data)/i.test(v)?v:'';}
function video(r){return /\.(?:webm|mp4)(?:[?#].*)?$/i.test(String(r||''));}
function yt(v){v=tx(v);let m=v.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?(?:.*&)?v=|embed\/|shorts\/|live\/))([\w-]{11})/i);return m?m[1]:(/^[\w-]{11}$/.test(v)?v:'');}
function media(el,r,opt={}){r=recurso(r);if(!el||!r)return el;let want=video(r)?'video':'img',cur=el.tagName.toLowerCase(),n=el;if(cur!==want){n=document.createElement(want);Array.from(el.attributes).forEach(a=>{if(!/^(src|poster|autoplay|loop|muted|playsinline|disablepictureinpicture)$/i.test(a.name))n.setAttribute(a.name,a.value)});el.replaceWith(n)}if(want==='video'){n.src=r;n.autoplay=true;n.loop=true;n.muted=true;n.playsInline=true;['autoplay','loop','muted','playsinline','disablepictureinpicture'].forEach(a=>n.setAttribute(a,''));try{n.load();let p=n.play();if(p&&p.catch)p.catch(()=>{})}catch(e){}}else{n.src=r;if(opt.alt)n.alt=opt.alt}if(opt.aria)n.setAttribute('aria-label',opt.aria);return n;}
function mask(el,r){r=recurso(r);if(!el||!r)return;let u='url("'+r.replace(/"/g,'%22')+'")';el.style.webkitMaskImage=u;el.style.maskImage=u;}
function label(a,t){if(!a||!t)return;let s=q('.web-nav-label',a);if(!s){Array.from(a.childNodes).filter(n=>n.nodeType===3).forEach(n=>n.remove());s=document.createElement('span');s.className='web-nav-label';a.appendChild(s)}s.textContent=t;}
function aplicarLogo(){let r=at(CFG,['header','logo']),a=q('#btnLogo');if(a&&r){let e=q('video,img',a);if(e)media(e,r,{alt:'LSPedia',aria:'Logo LSPedia'})}}
const MEN={diccionario:'btnInicio',vocabulario:'btnCategorias',herramientas:'btnHerramientas',nosotros:'btnSobreNosotros'};
function aplicarMenu(){let m=at(CFG,['header','menu'])||{};Object.keys(MEN).forEach(k=>{let x=m[k]||{},id=MEN[k],a=document.getElementById(id),t=tx(x.texto);if(a){if(t)label(a,t);mask(q('.nav-icono',a),x.icono)}let b=q('.mobile-bottom-nav .mbn-item[data-vinculado="'+id+'"]');if(b){let l=q('.mbn-label',b);if(l&&t)l.textContent=t;mask(q('.mbn-icon-img',b),x.icono)}})}
function titulo(el,tipo,t){if(!el||!t)return;el.textContent='';let p=t.split(/\s+/).filter(Boolean),n=tipo==='diccionario'&&p.length>1?2:1,s=document.createElement('span');s.className='titulo-acento';s.textContent=p.slice(0,n).join(' ');el.appendChild(s);if(p.length>n)el.appendChild(document.createTextNode(' '+p.slice(n).join(' ')));}
function subDic(t){let c=q('#subtituloPrincipal');if(!c||!t)return;c.textContent='';c.classList.remove('d-none');let i=document.createElement('span');i.className='aviso-mision-icono';i.setAttribute('aria-hidden','true');i.textContent='🤟';let d=document.createElement('div');d.className='aviso-mision-texto';t.split('\n').map(x=>x.trim()).filter(Boolean).forEach((x,j,a)=>{let p=document.createElement('p');p.className=j===a.length-1?'aviso-mision-linea2':'aviso-mision-linea1';p.textContent=x;d.appendChild(p)});c.append(i,d);}
function subVoc(t){let c=q('#vocabularioIntroLista');if(!c||!t)return;let ls=t.split('\n').map(x=>x.trim()).filter(Boolean),ic=['🔎','💡','🌎','🤝','🧩','✨'],it=qa('.vocab-intro-item',c);while(it.length<ls.length){let d=document.createElement('div');d.className='vocab-intro-item';d.innerHTML='<span class="vocab-intro-icono" aria-hidden="true"></span><p class="vocab-intro-texto"></p>';c.appendChild(d);it.push(d)}it.forEach((d,i)=>{d.style.display=i<ls.length?'':'none';if(i<ls.length){q('.vocab-intro-icono',d).textContent=ic[i%ic.length];q('.vocab-intro-texto',d).textContent=ls[i]}})}
function vista(){let b=q('#btnCategorias');return b&&b.classList.contains('active')?'vocabulario':'diccionario';}
function aplicarHero(tipo=vista()){let h=at(CFG,['heroes',tipo])||{},t=tx(h.titulo),s=ml(h.subtitulo);if(t)titulo(q('#tituloPrincipal'),tipo,t);if(tipo==='vocabulario'){if(s)subVoc(s)}else if(s)subDic(s);let a=q('#colAvatarHero .avatar-hero-img');if(a&&h.avatar)media(a,h.avatar,{alt:'Personaje visual de LSPedia',aria:'Personaje visual de LSPedia'});}
function aplicarRedes(){let s=at(CFG,['social'])||{};['tiktok','instagram','youtube','facebook'].forEach(k=>{let u=enlace(s[k]);if(!u)return;qa('.footer-red-'+k+',.stat2-red-'+k).forEach(a=>{if(a.tagName==='A'){a.href=u;a.target='_blank';a.rel='noopener noreferrer'}})})}
const ACC={sugerir:['.nosotros-apoyo-card-sugerencia','#modalSugerencia'],idea:['.nosotros-apoyo-card-idea','#modalEnviarIdea'],apoyar:['.nosotros-apoyo-card-donacion','#modalDonacion'],interprete:['.nosotros-apoyo-card-interprete','#modalInterprete']};
function abrir(u){if(/^https?:\/\//i.test(u))window.open(u,'_blank','noopener,noreferrer');else location.href=u;}
function aplicarAcciones(){let a=at(CFG,['acciones'])||{};Object.keys(ACC).forEach(k=>{let x=a[k]||{},u=enlace(x.url),n=tx(x.nombre),d=ml(x.contenido);qa(ACC[k][0]).forEach(c=>{if(n&&q('.nosotros-apoyo-titulo',c))q('.nosotros-apoyo-titulo',c).textContent=n;if(d&&q('.nosotros-apoyo-desc',c))q('.nosotros-apoyo-desc',c).textContent=d;if(u){c.removeAttribute('data-bs-toggle');c.removeAttribute('data-bs-target');c.dataset.webHref=u;c.setAttribute('role','link')}else{c.setAttribute('data-bs-toggle','modal');c.setAttribute('data-bs-target',ACC[k][1]);delete c.dataset.webHref;c.setAttribute('role','button')}if(!c.dataset.webListener){c.dataset.webListener='1';c.addEventListener('click',e=>{let z=c.dataset.webHref;if(!z)return;e.preventDefault();e.stopImmediatePropagation();abrir(z)},true);c.addEventListener('keydown',e=>{let z=c.dataset.webHref;if(z&&(e.key==='Enter'||e.key===' ')){e.preventDefault();abrir(z)}})}})})}
function p(txt){let e=document.createElement('p');e.className='text-secondary mb-3';e.style.lineHeight='1.7';e.textContent=txt;return e;}
function contenido(c,t){t=ml(t);if(!c||!t)return;c.textContent='';let par=[],ul=null;function flush(){let z=par.join(' ').trim();if(z)c.appendChild(p(z));par=[]}t.split('\n').forEach(l=>{l=l.trim();if(!l){flush();ul=null;return}if(/^(?:[-•]|\d+[.)])\s+/.test(l)){flush();if(!ul){ul=document.createElement('ul');ul.className='text-secondary mb-4';ul.style.lineHeight='1.9';c.appendChild(ul)}let li=document.createElement('li');li.textContent=l.replace(/^(?:[-•]|\d+[.)])\s+/,'');ul.appendChild(li)}else{ul=null;par.push(l)}});flush();}
function nuevoBloque(){let r=q('#nosotrosApoyoRow');if(!r||!r.parentNode)return null;let h=document.createElement('h4'),b=document.createElement('div');h.className='nosotros-titulo-clicable fw-bold mb-3';b.className='nosotros-bloque-clicable';[h,b].forEach(e=>{e.setAttribute('role','button');e.setAttribute('tabindex','0');r.parentNode.insertBefore(e,r)});return[h,b];}
function aplicarNosotros(){let s=at(CFG,['nosotros','secciones']);if(!Array.isArray(s)||!s.length)return;let r=q('#nosotrosTextoBajoVideo');if(!r)return;let hs=qa(':scope > .nosotros-titulo-clicable[data-tiempo-nosotros]',r);while(hs.length<s.length){let z=nuevoBloque();if(!z)break;hs.push(z[0])}hs.forEach((h,i)=>{let x=s[i],b=h.nextElementSibling;if(!x){h.style.display='none';if(b&&b.classList.contains('nosotros-bloque-clicable'))b.style.display='none';return}let sec=String(Math.max(0,Math.round(Number(x.tiempo)||0)));h.style.display='';h.dataset.tiempoNosotros=sec;h.textContent=tx(x.titulo)||'Sección';if(!b||!b.classList.contains('nosotros-bloque-clicable')){b=document.createElement('div');b.className='nosotros-bloque-clicable';h.after(b)}b.style.display='';b.dataset.tiempoNosotros=sec;b.setAttribute('role','button');b.setAttribute('tabindex','0');contenido(b,x.contenido)})}
function cambiarVideoNosotros(intentos=50){let id=yt(at(CFG,['nosotros','video']));if(!id)return;try{if(typeof ytPlayerNosotros!=='undefined'&&ytPlayerNosotros&&typeof ytPlayerNosotros.getVideoData==='function'){let a=(ytPlayerNosotros.getVideoData()||{}).video_id||'';if(a!==id&&typeof ytPlayerNosotros.loadVideoById==='function')ytPlayerNosotros.loadVideoById(id);return}}catch(e){}if(intentos>0)setTimeout(()=>cambiarVideoNosotros(intentos-1),120);}
function aplicar(){if(!CFG)return;aplicarLogo();aplicarMenu();aplicarRedes();aplicarAcciones();aplicarNosotros();aplicarHero();document.documentElement.dataset.webConfigLspedia='1';}
function navegacion(){['btnInicio','btnCategorias'].forEach(id=>{let e=document.getElementById(id);if(e&&!e.dataset.webHeroListener){e.dataset.webHeroListener='1';e.addEventListener('click',()=>{let t=id==='btnCategorias'?'vocabulario':'diccionario';setTimeout(()=>aplicarHero(t),80);setTimeout(()=>aplicarHero(t),350)})}});let n=q('#btnSobreNosotros');if(n&&!n.dataset.webVideoListener){n.dataset.webVideoListener='1';n.addEventListener('click',()=>setTimeout(()=>cambiarVideoNosotros(),250))}window.addEventListener('popstate',()=>setTimeout(()=>{aplicarHero();cambiarVideoNosotros()},200),{passive:true});}
async function cargar(){try{let u='data/web-config.json?v='+Date.now(),d;if(window.LSPediaCore&&LSPediaCore.leerJsonSeguro)d=await LSPediaCore.leerJsonSeguro(u,{timeoutMs:5000,reintentos:0,fetch:{cache:'no-store',credentials:'same-origin'}});else{let r=await fetch(u,{cache:'no-store'});if(!r.ok)return;d=await r.json()}if(!d||typeof d!=='object')return;CFG=d;window.LSPediaWebConfig=d;aplicar();navegacion();setTimeout(aplicar,500);setTimeout(()=>{aplicar();cambiarVideoNosotros()},1500)}catch(e){if(!e||e.status!==404)console.warn('[LSPedia] Configuración WEB no disponible; se conserva el contenido integrado.',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',cargar,{once:true});else cargar();
})();
